steps:
    -
        name: gcr.io/cloud-builders/docker
        args:
            - build
            - '-t'
            - 'gcr.io/$PROJECT_ID/mushymatch:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
            - .
    -
        name: gcr.io/cloud-builders/docker
        args:
            - tag
            - 'gcr.io/$PROJECT_ID/mushymatch:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
            - 'gcr.io/$PROJECT_ID/mushymatch:cloudbuild-$BRANCH_NAME-latest'
            
    -
        name: 'gcr.io/cloud-builders/docker'
        args:
            - push 
            - 'gcr.io/$PROJECT_ID/mushymatch:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
    -
            
        name: 'gcr.io/cloud-builders/docker'
        args:
            - push 
            - 'gcr.io/$PROJECT_ID/mushymatch:cloudbuild-$BRANCH_NAME-latest'
            
images:
          - 'gcr.io/$PROJECT_ID/mushymatch:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
          - 'gcr.io/$PROJECT_ID/mushymatch:cloudbuild-$BRANCH_NAME-latest'
